blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<slug:slug>', views.PostDetailView.as_view(), name='post_detail'),
    #path('tag/<slug:slug>', views.PostDetailView.as_view(), name='post_list_by_tag'),
    path('<slug:slug>/share', views.PostShareView.as_view(), name='share_post'),
    path('sharer/done', views.SharedPostView.as_view(), name='share_done'),
    path('contact/us', views.ContactUsView.as_view(), name='contact_us'),
    path('search/', views.SearchView.as_view(), name='search'),
]

tech_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from taggit.managers import TaggableManager
from django.urls import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    image = models.ImageField(upload_to='posts/%y/%m/%d', blank=True)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_post')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    url = models.URLField(null=True, blank=True)

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[#self.publish.year,
                              #self.publish.month,
                              #self.publish.day,
                              self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=200)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

class Feedback(models.Model):
    full_name = models.CharField(max_length=120)
    Email = models.EmailField()
    contact = models.CharField(max_length=13)
    subject = models.CharField(max_length=200,)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

    class Meta:
        ordering = ('-created',)

blog/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Submit
from crispy_forms.bootstrap import InlineRadios, InlineField

class EmailPostShare(forms.Form):
    name = forms.CharField(max_length=30, label='Your name')
    email = forms.EmailField(label='Email Address')
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(EmailPostShare, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-control'
        self.helper.layout = Layout(
            Row(
                Column('name', css_class='form-group col-md-6 mb-0'),
                Column('email', css_class='form-group col-md-6 mb-0'),
            ),
            'to',
            'comments',
            Submit('submit', 'Send', css_class='btn btn-block btn-primary')
        )

class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-control'
        self.helper.layout = Layout(
            Row(
                Column('name', css_class='form-group col-md-6 mb-0'),
                Column('email', css_class='form-group col-md-6 mb-0'),
            ),
            'body',
            Submit('submit', 'Add comment', css_class='btn btn-block btn-primary')
        )

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        labels = {
            'name': _('Your name'),
            'email': _('Your Email Address'),
            'body': _('Your Comment')
        }
        

class SearchForm(forms.Form):
    query = forms.CharField(label='Search Here')

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'inlineFormInputGroupUsername'
        self.helper.form_class = 'form-control'

class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=30, label='Your name')
    email = forms.EmailField(label='Email Address')
    subject = forms.CharField(max_length=180)
    message = forms.CharField(widget=forms.Textarea)
    

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form_control'
        self.helper.layout = Layout(

            Row(
                Column('name', css_class='form-group col-md-6 mb-0'),
                Column('email', css_class='form-group col-md-6 mb-0'), 
            ),                                                       
            'subject',
            'message',
            Submit('submit', 'Send', css_class='btn btn-block btn-primary')
        )
        

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from .models import Comment, Post, Feedback
from .forms import EmailPostShare, CommentForm, FeedbackForm
from django.db.models import Count
import time
from django.core.mail import send_mail
from django.views import generic
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery

# Create your views here.
class PostListView(generic.ListView):
    queryset = Post.published.all()
    paginate_by = 5
    template_name = 'blog/post/post_list.html'
    context_object_name = 'posts'
        

class PostDetailView(generic.DetailView, generic.FormView):
    queryset = Post.published.all()
    form_class = CommentForm
    template_name = 'blog/post/post_detail.html'

    def form_valid(self, form):
        self.object = self.get_object()
        new_comment = form.save(commit=False)
        new_comment.post = self.object
        new_comment.save()

        return redirect(reverse('blog:post_detail', kwargs={'slug': self.object.slug}))

    def get_context_data(self, **kwargs):
        self.object = self.get_object()
        ctx = super().get_context_data(**kwargs)
        post_tags_ids = self.object.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=self.object.id)
        ctx['similar_posts'] = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
        ctx['comments'] = self.object.comments.filter(active=True)
        return ctx



class PostShareView(generic.FormView, generic.DetailView):
    queryset = Post.published.all()
    form_class = EmailPostShare
    template_name = 'blog/post/share.html'
    context_object_name = 'post'
    
    def form_valid(self, form):
        self.object = self.get_object()
        cd = form.cleaned_data
        post_url = self.request.build_absolute_uri(self.object.get_absolute_url())
        subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], self.object.title)
        message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(self.object.title, post_url, cd['name'], cd['comments'])
        send_mail(subject, message, 'admin@myblog.com', [cd['to']])

        return redirect(reverse_lazy('blog:share_done'))
    

class SharedPostView(generic.TemplateView):
    template_name = 'blog/post/share_done.html'

class PostCommentView(generic.FormView, generic.DetailView):
    queryset = Post.published.all()
    form_class = CommentForm
    template_name = 'blog/post/share.html'

class ContactUsView(generic.TemplateView, generic.FormView):
    template_name = 'blog/feedback.html'
    form_class = FeedbackForm
    sent = False

    def form_valid(self, form):
        cd = form.cleaned_data
        subject = '{} ({}) Feedback'.format(cd['name'], cd['email'])
        message = cd['message']
        sender = cd['email']
        send_mail(subject, message, sender, ['admin@myblog.com'])
        self.sent = True

        return redirect(reverse_lazy('blog:contact_us'))

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['sent'] = self.sent
        return ctx

class SearchView(generic.View):
    def get(self, request, *args, **kwargs):
        queryset = Post.published.all()
        query = request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) |
                Q(overview__icontains=query)                
            ).distinct()
        
        context = {
            'result': queryset,
            'query': query
        }

        return render(request, 'blog/post/search.html', context)

templates/blog/post/latest_posts.html
{% for post in latest_posts %}
							<a href="#"> <div class="item d-flex align-items-center">
                                    <div class="image">
                                        <img src="img/small-thumbnail-1.jpg" alt="..." class="img-fluid">
                                    </div>
                                    <div class="title">
                                        <strong>{{ post.title }}</strong>
                                        <div class="d-flex align-items-center">
                                            <div class="views">
                                                <i class="icon-eye"></i> 500
                                            </div>
                                            {% total_comments post.id as all_comments %}
                                            <div class="comments">
                                                <i class="icon-comment"></i>{{ all_comments }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
{% endfor %}

templates/blog/post/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load social_share %}
{% load blog_tags %}

{% block title %}{{ post.title }}{{ block.super }}{% endblock %}

{% block content %}
				<!-- Latest Posts -->
                <main class="post blog-post col-lg-12"> 
                    <div class="container-fluid">
                        <div class="post-single">
                            <div class="post-thumbnail">
                                <img src="{% if post.image %}{{ post.image.url }}{% else %}{% static 'img/blog-post-techblog-1.jpeg' %}{% endif %}" alt="..." class="img-fluid">
                            </div>
                            <div class="post-details">
                                <div class="post-meta d-flex justify-content-between">
                                    <div class="category">
                                        <a href="#">Business</a>
                                        <a href="#">Financial</a>
                                    </div>
                                </div>
                                <h1>{{ post.title }}<a href="#"><i class="fa fa-bookmark-o"></i></a></h1>
                                <div class="post-footer d-flex align-items-center flex-column flex-sm-row">
                                    <a href="#" class="author d-flex align-items-center flex-wrap"> <div class="avatar">
                                            <img src="{% static 'img/avatar.png' %}" alt="..." class="img-fluid">
                                        </div> <div class="title">
                                            <span>{{ post.author }}</span>
                                        </div></a>
                                    <div class="d-flex align-items-center flex-wrap"> 
                                        <div class="date">
                                            <i class="icon-clock"></i> {{ post.publish|time:"H\h i\m" }} Ago
                                        </div>
                                        <div class="views">
                                            <i class="icon-eye"></i> 500
                                        </div>
                                        {% total_comments post.id as all_comments %}
                                        <div class="comments meta-last">
                                            <i class="icon-comment"></i>{{ all_comments }}
                                        </div>
                                    </div>
                                </div>
                                <div class="post-body">
                                    <p class="lead">{{ post.body|linebreaks }}.</p>
                                    <p> <img src="{% static 'img/blog-post-techblog-1.jpeg' %}" alt="..." class="img-fluid"></p>
                                    <h3>Lorem Ipsum Dolor</h3>
                                    <p>div Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda temporibus iusto voluptates deleniti similique rerum ducimus sint ex odio saepe. Sapiente quae pariatur ratione quis perspiciatis deleniti accusantium</p>
                                    <blockquote class="blockquote">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
                                        <footer class="blockquote-footer">Someone famous in
                                            <cite title="Source Title">Source Title</cite>
                                        </footer>
                                    </blockquote>
                                    {% lorem 2 p %}
                                </div>
                                <div class="post-tags">
                                    {% for tag in post.tags.all %}
                                    <a href="#" class="tag">{{ tag }}</a>
                                    {% endfor %}
                                </div>
                                <div class="mt-2 d-flex justify-content-between border border-dark p-3">
                                    <h5 class="text-primary">
                                Share via</h5>
                                    <ul class="social-menu">
                                        <li class="list-inline-item">
                                            {% post_to_facebook object_or_url '<i class="fa fa-facebook share-facebook"></i>' %}
                                        </li>
                                        <li class="list-inline-item">
                                            {% post_to_twitter '{{ post.title }}. Check it out!' object_or_url '<i class="fa fa-twitter"></i>' %}
                                        </li>
                                        <li class="list-inline-item">
                                            {% post_to_whatsapp object_or_title '<i class="fa fa-whatsapp"></i>' %}
                                        </li>
                                        <li class="list-inline-item">
                                            <a href="{% url 'blog:share_post' post.slug %}"><i class="fa fa-envelope"></i></a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="posts-nav d-flex justify-content-between align-items-stretch flex-column flex-md-row">
                                    {% for post in similar_posts %}
                                    <a href="{{ post.get_absolute_url }}" class="prev-post text-left d-flex align-items-center">   <div class="icon prev">
                                            <i class="fa fa-angle-left"></i>
                                        </div> 
                                        
                                        <div class="text">
                                            
                                            <h6>{{ post.title }}</h6>
                                            <strong class="text-primary"> By {{ post.author }} </strong>
                                        </div>
                                    </a>
                                    {% endfor %}
                                </div>
                                <div class="post-comments">
                                    {% with comments.count as total_comments %}
                                    <header>
                                        <h3 class="h6">Post Comments<span class="no-of-comments">({{ total_comments }})</span></h3>
                                    </header>
                                    {% endwith %}
                                    {% for comment in comments %}
                                    <div class="comment shadow-sm p-2 mt-5">
                                        <div class="comment-header d-flex justify-content-between">
                                            <div class="user d-flex align-items-center">
                                                <div class="image">
                                                    <img src="{% static 'img/avatar.png' %}" alt="..." class="img-fluid rounded-circle">
                                                </div>
                                                <div class="title">
                                                    <strong>{{ comment.name }}</strong>
                                                    <span class="date">{{ comment.created|date:"M Y" }}</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="comment-body">
                                            <p>{{ comment.body }}.</p>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                <div class="add-comment">
                                    <header>
                                        <h3 class="h6">Leave a reply</h3>
                                    </header>
                                    <form action="#" class="commenting-form" method="post">
                                        {% csrf_token %}
                                        {% crispy form %}
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
{% endblock %}

templates/blog/post/post_list.html
{% extends "base.html" %}
{% load blog_tags %}
{% load static %}

{% block content %}
	{% for post in posts %}
							<div class="post col-xl-6 border-dark shadow-sm p-3">
                                <div class="post-thumbnail">
                                    <a href="post.html"><img src="{% static 'img/blog-post-techblog-1.jpeg' %}" alt="..." class="img-fluid"></a>
                                </div>
                                <div class="post-details">
                                    <div class="post-meta d-flex justify-content-between text-muted bg-white">
                                        <div class="date meta-last">
                                            {{ post.publish|date:"d M | Y" }}
                                        </div>
                                        <div class="category">
                                            {% for tag in post.tags.all %}
                                            <a href="#">{{ tag|slice:"1:" }}</a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <a href="{{ post.get_absolute_url }}"> <h3 class="h4">{{ post.title }}</h3></a>
                                    <p class="text-muted">{{ post.body|truncatewords:10 }}</p>
                                    <footer class="post-footer d-flex align-items-center">
                                        <a href="#" class="author d-flex align-items-center flex-wrap"> <div class="avatar">
                                                <img src="{% static 'img/avatar.png' %}" alt="{{ post.author }}" class="img-fluid" width="200">
                                            </div> <div class="title">
                                                <span>{{ post.author }}</span>
                                            </div></a>
                                        <div class="date">
                                            <i class="icon-clock"></i> {{ post.publish|timesince }}
                                        </div>
                                        {% total_comments post.id as all_comments %}
                                        <div class="comments meta-last">
                                            <i class="icon-comment"></i>{{ all_comments }}
                                        </div>
                                    </footer>
                                </div>
                            </div>
    {% empty %}
    	No Post Yet
    {% endfor %}
{% endblock %}
{% block pagination %}
{% include "blog/pagination.html" with page=page_obj %}
{% endblock %}

templates/blog/post/search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load blog_tags %}
{% load static %}

{% block title %}Search{% endblock %}
{% block hot %}
{% endblock %}

{% block content %}
	{% if query %}
		<h5><a href="{% url 'blog:post_search' %}" class="text-nav-green">Search again</a></h5>
		<hr>
		<p class="lead text-muted">
			{% with results.count as total_results %}
				Found {{ total_results }} result{{ total_results|pluralize }} in <label class="text-green">"{{ query }}"</label>
			{% endwith %}
		</p>

		<ul class="list-group">
		<div class="row">
		 {% for post in results %}
		 	<div class="col-md-6">
		        <div class="card mb-4 shadow-sm">
		            <a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" class="card-img-top" alt="..." height="200"></a>
				    <div class="card-body">
				        <div class="post-meta mb-2">
	                        {% for tag in post.tags.all %}
						       	  <a class="post-category cat-2" href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
						       	  {% if not forloop.last %}, {% endif %}
						    {% endfor %}
	                        <span class="post-date">{{ post.publish|date:"d F Y" }}</span>
	                    </div>
				        <a href="{{ post.get_absolute_url }}"><p class="card-title">{{ post.title|title }} on Verte Africa</p></a>
				        <div class="d-flex justify-content-between align-items-center">
					        <div class="btn-group">
					            <div class="post-meta">
		                            <i class="fa fa-user icon-colors" aria-hidden="true"></i>
		                            <span class="post-date text-muted">
		                            	<a href="{% url 'user:author_info' post.author %}">
								  			<label class="ml-1">{{ post.author }}</label>
								  		</a>
								  	</span>
		                        </div>
					        </div>
					        {% total_comments post.id as all_comments %}
					        <i class="fa fa-comments ml-auto icon-colors" aria-hidden="true"></i><small class="text-muted ml-1">{{ all_comments }} Comment{{ all_comments|pluralize }}</small>
				        </div>
				    </div>
		        </div>
		    </div>
		 {% empty %}
		  <p class="text-muted ml-3">There are no results for your query.</p>
		  	<div class="col-md-12 mt-5 mb-5">
				<a href="#"><img src="{% static 'img/footer-add.gif' %}" class="card-img-top" alt="ads"></a>
			</div>
		 {% endfor %}
		</div>
	{% else %}
		<h3>Search for posts</h3>
		<form action="." method="get">
		  <div class="form-row align-items-center mb-5">
		    <div class="col-md-12 my-1">
		      <div class="input-group">
		        <input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Search Here" name="query">
		        <div class="input-group-prepend">
		          <button type="submit" class="btn bg-green"><span class="text-white">Search</span></button>
		        </div>
		      </div>
		    </div>
		  </div>
		</form>
	{% endif %}

{% endblock %}
{% block sidebar %}
<div class="col-md-12">
	<a href="#"><img src="{% static 'img/sidebar-ads.jpg' %}" class="card-img-top" alt="ads"></a>
</div>
<div class="col-md-12 mt-5">
	<a href="#"><img src="{% static 'img/hero-add.gif' %}" class="card-img-top" alt="ads"></a>
</div>
<div class="col-md-12 mt-5">
	<a href="#"><img src="{% static 'img/sidebar-ads.jpg' %}" class="card-img-top" alt="ads"></a>
</div>
{% endblock %}
{% block pagination %}
{% endblock %}

templates/blog/post/share.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Share "{{ post.title }}" {{ block.super }}{% endblock %}

{% block content %}
				<main class="post blog-post col-lg-11 bg-light shadow-sm"> 
                    <div class="container">
                    	<header>
						    <h3 class="h6">Share "{{ post.title }}"</h3>
						</header>
                        <div class="post-single">
						 	<div class="add-comment">
						        <form action="" class="commenting-form" method="post">
						        	{% csrf_token %}
						            {% crispy form %}
						        </form>
						    </div>
						</div>
					</div>
				</main>
{% endblock %}

templates/blog/post/share_done.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Artical shared successfully {{ block.super }}{% endblock %}

{% block content %}
				<main class="post blog-post col-lg-12"> 
                    <div class="container">
                        <div class="post-single">
						 	<div class="add-comment">
						        <div class="alert alert-success" role="alert">
								  Article successfuly shared vie email
								</div>
						    </div>
						</div>
					</div>
				</main>
{% endblock %}